name: Node npm publish
description: "Run npm publish on the project after dependencies have been installed."


inputs:
  working_directory:
    description: "Directory to run npm publish in (default: repository root)"
    required: false
    type: string
    default: "."
  
  access_level:
    description: "The access level for the npm package (e.g., public or restricted)"
    required: false
    type: string
    default: "public"

  node_access_token:
    description: "The npm access token to authenticate publishing"
    required: true
    type: string

outputs:
  npm_publish_exit_code:
    description: "The exit code from the npm publish command"
    value: ${{ steps.npm_publish.outputs.exit_code }}

runs:
  using: "composite"

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Run npm publish
      id: npm_publish
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node_access_token }}
      run: |
        set +e
        npm publish --access=${{ inputs.access_level }}
        EXIT_CODE=$?
        set -e
        
        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
