name: Node npm audit
description: "Run npm audit on the project after dependencies have been installed."

inputs:
  working_directory:
    description: "Directory to run npm audit in (default: repository root)"
    required: false
    type: string
    default: "."

  audit_level:
    description: "The minimum level of vulnerability for npm audit to exit with a non-zero exit code (eg info, low, moderate, high, critical, or none)"
    required: false
    type: string
    default: "low"

outputs:
  npm_audit_exit_code:
    description: "The exit code from the npm audit command"
    value: ${{ steps.npm_audit.outputs.exit_code }}

runs:
  using: "composite"

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Run npm Audit
      id: npm_audit
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set +e
        npm audit --audit-level ${{ inputs.audit_level }}
        EXIT_CODE=$?
        set -e
        
        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
