name: Node npm lint
description: "Run npm lint on the project after dependencies have been installed."

inputs:
  working_directory:
    description: "Directory to run npm lint in (default: repository root)"
    required: false
    type: string
    default: "."

outputs:
  npm_lint_exit_code:
    description: "The exit code from the npm lint command"
    value: ${{ steps.npm_lint.outputs.exit_code }}

runs:
  using: "composite"

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install Node Dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: npm ci

    - name: Run npm lint
      id: npm_lint
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        npm run lint

        EXIT_CODE=$?
        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
